config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :lists, only: %i[index show new create edit update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
  resources :lists, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.where.not(id: @list.movies).order(title: :asc)
  end

  def create
    @bookmark = Bookmark.new(list_params)
    @list = List.find(params[:list_id])
    @movie = Movie.find(list_params[:movie_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def list_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="mt-4 container">
  <%= link_to "<- back", list_path(@list), class: "btn btn-primary"%>
</div>

<div class="mt-4 container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: @movies, include_blank: false%>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="min-vh-100 d-flex flex-column">
    <nav class="navbar navbar-expand-lg navbar-dark px-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <%= image_tag "logo.png", alt: "text", class: "logo" %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item ms-auto">
              <%= link_to "home", lists_path %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main class="flex-grow-1">
      <%= yield %>
    </main>
    <div class="mt-4 d-flex justify-content-center footer">
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/index.html.erb
<% random_movie = @movies.sample %>

<div class="banner d-flex align-items-center" style="background-image: linear-gradient(rgba(2, 6, 23, 0),rgba(2, 6, 23, 0.8)), url(<%= random_movie.poster_url %>);">
  <div class="container banner-text">
    <h1>Watch the greatest movies</h1>
    <p>Featured: <%= random_movie.title %></p>
  </div>
</div>

<div class="container">
  <%= link_to "+ Add a list!", new_list_path, class: "mt-4 btn btn-primary rounded rounded-lg"%>
  <div class="cards mt-4">
  <% if @lists.any? %>
    <% @lists.each do |list| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? (cl_image_path list.photo.key, height: 300, crop: :fill) : list.movies.any? ? image_path(list.movies.sample.poster_url) : image_path('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU') %>)">
          <h2><%= list.name %></h2>
        <%= link_to "", list_path(list), class: "list" %>
          <div class="card-buttons">
            <%= link_to edit_list_path(list) do %>
              <i class="fa-solid fa-pencil"></i>
            <% end %>
            <%= link_to list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
      </div>
    <% end %>
  <% else %>
    <h2>There are no lists yet!</h2>
  <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="mt-4 container">
  <%= link_to "<- back", lists_path, class: "btn btn-primary"%>
</div>

<div class="mt-4 container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="mt-4 container">
  <%= link_to "<- back", lists_path, class: "btn btn-primary"%>
  <%= link_to "+ Add movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
  <h1 class="mt-4"><%= @list.name %> Movies</h1>

  <% unless @list.movies.any? %>
    <p>There are no movies in this list!</p>
  <% end %>

  <div class="cards">
    <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list_id: @list.id, movie_id: movie.id) %>
    <div class="card-category p-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= movie.poster_url %>)">
      <div class="card-buttons">
        <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
      <h2><%= movie.title%></h2>
      <div class="card-rating">
        <p><%= movie.rating %> <i class="fa-solid fa-star"></i></p>
      </div>
    </div>
    <% end %>
  </div>
</div>